language: php

php:
  - 5.5
 

before_script:
  -  composer install
  -  mkdir -p shippable/codecoverage
  -  mkdir -p shippable/testresults
script: 
  -  php -v
 # -  phpunit  --log-junit shippable/testresults/junit.xml tests/
  #-  phpunit --coverage-xml  shippable/codecoverage/  tests/
  - phpunit --log-junit shippable/testresults/junit.xml --bootstrap tests/bootstrap.php tests
  - phpunit --coverage-xml shippable/codecoverage/ --bootstrap tests/bootstrap.php tests

matrix:
  include:
   - php: 5.6
